### Get all projects
GET http://localhost:8080/projects

### Get project by ID
GET http://localhost:8080/projects/6

### Create project
POST http://localhost:8080/projects/create
Content-Type: application/json

### Update project
PUT http://localhost:8080/projects/update/111
Content-Type: application/json

### Delete project
DELETE http://localhost:8080/projects/delete/10
